version: '3.10'



networks:
  dev_network:
    driver: bridge

services:
  fastapi_app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:80"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: api_db 
      POSTGRES_PORT: 5432
    networks:
      - dev_network
    depends_on:
      api_db:
        condition: service_healthy
    restart: unless-stopped

  api_db:
    image: postgres:16.2-alpine3.19
    env_file: .env
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - dev_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
